

services:
  api-service:
    build: ./api
    container_name: backend-api
    networks:
      - internal-yossi-net
    environment:
      - PORT=3000
    restart: always

  web-service:
    build: ./web
    container_name: frontend-web
    ports:
      - "9090:80"
    networks:
      - internal-yossi-net
    restart: always

networks:
  internal-yossi-net:
    driver: bridge